LIBS = -lpthread

all: multithread_practice multithread_practice_solution

CC = gcc

multithread_practice: multithread_practice.c
		$(CC) -o $@ $<

multithread_practice_solution: multithread_practice_solution.c
		$(CC) -o $@ $< $(LIBS)
